version: "3.8"

services:

  mongodb:
    image: mongo:6.0
    container_name: movie-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ml-service:
    build: ../ml-service
    container_name: movie-ml
    ports:
      - "8000:8000"

  backend:
    build: ../backend
    container_name: movie-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/movie-recommendations
      - PORT=5000
      - ML_SERVICE_URL=http://ml-service:8000/recommend
      - JWT_SECRET=supersecretkey123
    depends_on:
      - ml-service
      - mongodb

volumes:
  mongo-data: